[package]
name = "compress-enum-vec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cev = { path = "./cev" }
cev_macros = { path = "./cev_macros" }

[workspace]
members = ["cev", "cev_macros"]
